{{- if eq .Values.deploy.controller true }}
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: baremetal-csi-controller
spec:
  serviceName: "csi-do"
  replicas: 1
  selector:
    matchLabels:
      app: baremetal-csi-controller
      role: csi-do
  template:
    metadata:
      labels:
        app: baremetal-csi-controller
        role: csi-do
    spec:
      serviceAccount: csi-controller-sa
      containers:
      # ********************** EXTERNAL-PROVISIONER sidecar container definition **********************
      - name: csi-provisioner
        image: {{ .Values.global.registry }}/csi-provisioner:{{ .Values.provisioner.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - "--csi-address=$(ADDRESS)"
        - "--v=5"
        - "--feature-gates=Topology=true"
        # TODO: remove AK8S-58
        - "--timeout=60s"
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      # ********************** EXTERNAL_ATTACHER sidecar container definition **********************
      - name: csi-attacher
        image: {{ .Values.global.registry }}/csi-attacher:{{ .Values.attacher.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - "--v=5"
        - "--csi-address=$(ADDRESS)"
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      # ********************** baremetal-csi-controller container definition **********************
      # TODO: Make CSI containers name smaller - AK8S-57
      - name: controller
        {{- if .Values.controller.image.tag }}
        image: {{ .Values.global.registry }}/baremetal-csi-plugin-controller:{{ .Values.controller.image.tag }}
        {{- else }}
        image: {{ .Values.global.registry }}/baremetal-csi-plugin-controller:{{ .Values.image.tag }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - "--endpoint=$(CSI_ENDPOINT)"
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: logs
          mountPath: /var/log
      volumes:
      - name: logs
        emptyDir: {}
      - name: socket-dir
        hostPath:
          path: /var/baremetal-csi/controller
          type: DirectoryOrCreate
{{- end }}
