kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: baremetal-csiplugin
spec:
  selector:
    matchLabels:
      app: baremetal-csiplugin
  template:
    metadata:
      labels:
        app: baremetal-csiplugin
    spec:
      serviceAccountName: csi-driver-registrar
      containers:
      # ********************** DRIVER-REGISTRAR sidecar container definition **********************
        - name: csi-node-driver-registrar
          image: {{ .Values.global.registry }}/csi-node-driver-registrar:{{ .Values.nodeDriverRegistrar.image.tag }}
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/baremetal-csi /registration/baremetal-csi-reg.sock"]
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/baremetal-csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: csi-socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
        # ********************** baremetal-csi-PLUGIN container definition **********************
        - name: baremetal-csi-plugin
          image: {{ .Values.global.registry }}/baremetal-csi-plugin:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          {{- if eq .Values.csiDriver.lvmMode true }}
          lifecycle:
            preStop:
              exec:
                command: ["/usr/bin/curl", "127.0.0.1:9999/rlvm"]
          {{ end }}

          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--controller=false"
            - --lmvmode={{ .Values.csiDriver.lvmMode }}
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          volumeMounts:
          - name: logs
            mountPath: /var/log
          - name: host-dev
            mountPath: /dev
          - name: csi-socket-dir
            mountPath: /csi
          - name: mountpoint-dir
            mountPath: /var/lib/kubelet/pods
            mountPropagation: "Bidirectional"
        - name: log-collector
          image: busybox:{{ .Values.busybox.image.tag }}
          args: [/bin/sh, -c, 'sleep 1; tail -n+1 -f /var/log/logrus.log']
          volumeMounts:
          - name: logs
            mountPath: /var/log
      volumes:
      - name: logs
        emptyDir: {}
      - name: host-dev
        hostPath:
          path: /dev
          type: Directory
      - name: csi-socket-dir
        hostPath:
          path: /var/lib/kubelet/plugins/baremetal-csi
          type: DirectoryOrCreate
      - name: registration-dir
        hostPath:
          path: /var/lib/kubelet/plugins_registry/
          type: DirectoryOrCreate
            # This volume is where the driver mounts volumes
      - name: mountpoint-dir
        hostPath:
          path: /var/lib/kubelet/pods
          type: Directory

