{{- if eq .Values.logReceiver.type "Elasticsearch"}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-csi-logs-config
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     info
        Daemon        off
        Parsers_File  fluent-parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    [INPUT]
        Name             tail
        Path             /var/log/csi.log
        DB               /var/log/flb.db
        Path_Key         filename
        Parser           csi-logs
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  Off
        Refresh_Interval 10

    [OUTPUT]
        Name            es
        Match           *
{{- if eq .Values.logReceiver.protocol "http"}}
        tls             Of
{{- else}}
        tls             On
        HTTP_User       {{ .Values.logReceiver.user }}
        HTTP_Passwd     {{ .Values.logReceiver.password }}
        tls.verify      Off
{{- end}}
        Type            logEvent
        Host            {{ .Values.logReceiver.host }}
        Port            {{ .Values.logReceiver.port }}
        Logstash_Format On
        Retry_Limit     False

  fluent-parsers.conf: |
    [PARSER]
        Name        csi-logs
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S %z

{{- end}}
