kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-do-controller
spec:
  serviceName: "csi-do"
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-do-controller
        role: csi-do
    spec:
      # priorityClassName: system-cluster-critical
      serviceAccount: csi-controller-sa
      containers:
      # ********************** EXTERNAL-PROVISIONER sidecar container definition **********************
      - name: csi-provisioner
        image: 10.244.120.194:8085/csi-provisioner:v1.0.1
        args:
        - "--provisioner=baremetal-csi"
        - "--csi-address=$(ADDRESS)"
        - "--v=5"
        - "--feature-gates=Topology=true"
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      # ********************** EXTERNAL_ATTACHER sidecar container definition **********************
      - name: csi-attacher
        image: 10.244.120.194:8085/csi-attacher:v1.0.1
        args:
        - "--v=5"
        - "--csi-address=$(ADDRESS)"
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      # ********************** CLUSTER-DRIVER-REGISTRAR sidecar container definition **********************
      - name: csi-cluster-driver-registrar
        image: 10.244.120.194:8085/csi-cluster-driver-registrar:v1.0.1
        args:
        - "--v=5"
        - "--pod-info-mount-version=\"v1\""
        - "--csi-address=$(ADDRESS)"
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        volumeMounts:
        - name: socket-dir
          mountPath: /csi
      # ********************** baremetal-csi-PLUGIN container definition **********************
      - name: baremetal-csi-controller
        image: 10.244.120.194:8085/baremetal-csi-plugin:alpha-14
        imagePullPolicy: Always
        args:
        - "--endpoint=$(CSI_ENDPOINT)"
        - "--nodeid=$(KUBE_NODE_NAME)"
        - "--startrest=false"
        env:
        - name: CSI_ENDPOINT
          value: unix:///csi/csi.sock
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName

        volumeMounts:
        - name: socket-dir
          mountPath: /csi
        - name: logs
          mountPath: /var/log

      - name: log-collector
        image: busybox
        args: [/bin/sh, -c, 'sleep 1; tail -n+1 -f /var/log/logrus.log']
        volumeMounts:
        - name: logs
          mountPath: /var/log
      volumes:
      - name: logs
        emptyDir: {}
      - name: socket-dir
        hostPath:
          path: /tmp/baremetal-csi
          type: DirectoryOrCreate
